# load dataset

In [33]:
import pandas as pd
df1 = pd.read_csv("student-scores.csv")
df = df1.copy()
df.head()

absence_days  biology_score   career_aspiration  chemistry_score  \
0             3             63              Lawyer               97   
1             2             99              Doctor               80   
2             9             65  Government Officer               96   
3             5             35              Artist               39   
4             5             80             Unknown               65   

   economics_score                                  email  english_score  \
0              NaN         paul.casey.1@gslingacademy.com             90   
1              NaN  danielle.sandoval.2@gslingacademy.com             73   
2              NaN       tina.andrews.3@gslingacademy.com             76   
3              NaN         tara.clark.4@gslingacademy.com             88   
4              NaN     anthony.campos.5@gslingacademy.com             74   

   extracurricular_activities first_name  gender  geography_score  \
0                        True       Paul    male               87   
1                       False   Danielle  female               63   
2                        True       Tina  female               87   
3                        True       Tara  female               37   
4                       False    Anthony    male               76   

   history_score  id last_name  math_score  part_time_job  physics_score  \
0             90   1     Casey          73          False             93   
1             67   2  Sandoval          82          False             78   
2             91   3   Andrews          81          False             95   
3             88   4     Clark          35          False             45   
4             77   5    Campos          84          False             65   

   weekly_self_study_hours  
0                       27  
1                       47  
2                       13  
3                        3  
4                       10

In [34]:
df['career_aspiration'].unique()

array(['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
       'Software Engineer', nan, 'Teacher', 'Business Owner', 'Scientist',
       'Banker', 'Writer', 'Accountant', 'Designer',
       'Construction Engineer', 'Game Developer', 'Stock Investor',
       'Real Estate Developer'], dtype=object)

In [35]:
df['career_aspiration'].value_counts()

career_aspiration
Software Engineer        315
Business Owner           309
Unknown                  222
Banker                   169
Lawyer                   138
Accountant               126
Doctor                   119
Real Estate Developer     83
Stock Investor            73
Construction Engineer     68
Artist                    67
Game Developer            63
Government Officer        61
Teacher                   59
Designer                  56
Scientist                 39
Writer                    32
Name: count, dtype: int64

# drop irrelevant columns

In [36]:
df.columns
df.drop(columns=['id','first_name','last_name','email'],axis=1, inplace=True)

In [37]:
# Define a list of mark columns (adjust if needed)
marks_columns = [
    'math_score', 'history_score', 'physics_score', 'chemistry_score',
    'biology_score', 'english_score', 'geography_score','economics_score'
]

# Fill NaN only in those columns with 0
df[marks_columns] = df[marks_columns].fillna(0)


# Replace blank or missing values in 'Career Aspiration' with "Unknown"
df['career_aspiration'] = df['career_aspiration'].replace('', 'Unknown')
df['career_aspiration'] = df['career_aspiration'].fillna('Unknown')

df['career_aspiration'].unique()



array(['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
       'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
       'Banker', 'Writer', 'Accountant', 'Designer',
       'Construction Engineer', 'Game Developer', 'Stock Investor',
       'Real Estate Developer'], dtype=object)

In [38]:
df = df[df['career_aspiration'] != 'Unknown']
df = df[df['career_aspiration'] != 'Game Developer']
df = df[df['career_aspiration'] != 'Real Estate Developer']
df = df[df['career_aspiration'] != 'Stock Investor']
df = df[df['career_aspiration'] != 'Construction Engineer']
df = df[df['career_aspiration'] != 'Designer']
df = df[df['career_aspiration'] != 'Artist']

# create new features from all score

In [39]:
df["total_score"] = df["math_score"] + df["history_score"] + df["physics_score"] + df["chemistry_score"] + df["biology_score"] + df["english_score"] + df["geography_score"] + df["economics_score"]
df["average_score"] = df["total_score"] / 8
df.head()

absence_days  biology_score   career_aspiration  chemistry_score  \
0             3             63              Lawyer               97   
1             2             99              Doctor               80   
2             9             65  Government Officer               96   
6             3             88   Software Engineer               73   
7             2             84   Software Engineer               63   

   economics_score  english_score  extracurricular_activities  gender  \
0              0.0             90                        True    male   
1              0.0             73                       False  female   
2              0.0             76                        True  female   
6              0.0             76                        True    male   
7              0.0             70                        True    male   

   geography_score  history_score  math_score  part_time_job  physics_score  \
0               87             90          73          False             93   
1               63             67          82          False             78   
2               87             91          81          False             95   
6               64             96          98          False             89   
7               85             95          92           True             94   

   weekly_self_study_hours  total_score  average_score  
0                       27        593.0         74.125  
1                       47        542.0         67.750  
2                       13        591.0         73.875  
6                       25        584.0         73.000  
7                       30        583.0         72.875

In [40]:
df.head()

absence_days  biology_score   career_aspiration  chemistry_score  \
0             3             63              Lawyer               97   
1             2             99              Doctor               80   
2             9             65  Government Officer               96   
6             3             88   Software Engineer               73   
7             2             84   Software Engineer               63   

   economics_score  english_score  extracurricular_activities  gender  \
0              0.0             90                        True    male   
1              0.0             73                       False  female   
2              0.0             76                        True  female   
6              0.0             76                        True    male   
7              0.0             70                        True    male   

   geography_score  history_score  math_score  part_time_job  physics_score  \
0               87             90          73          False             93   
1               63             67          82          False             78   
2               87             91          81          False             95   
6               64             96          98          False             89   
7               85             95          92           True             94   

   weekly_self_study_hours  total_score  average_score  
0                       27        593.0         74.125  
1                       47        542.0         67.750  
2                       13        591.0         73.875  
6                       25        584.0         73.000  
7                       30        583.0         72.875

# Encoding Categorical Columns

In [41]:
# from sklearn.preprocessing import LabelEncoder

# # Create a LabelEncoder object
# label_encoder = LabelEncoder()

# # Encode categorical columns using label encoder
# df['gender'] = label_encoder.fit_transform(df['gender'])
# df['part_time_job'] = label_encoder.fit_transform(df['part_time_job'])
# df['extracurricular_activities'] = label_encoder.fit_transform(df['extracurricular_activities'])
# df['career_aspiration'] = label_encoder.fit_transform(df['career_aspiration'])
# Define mapping dictionaries for categorical features
gender_map = {'male': 0, 'female': 1}
part_time_job_map = {False: 0, True: 1}
extracurricular_activities_map = {False: 0, True: 1}
'''
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2, 'Artist': 3, 'Unknown': 4,
        'Software Engineer': 5, 'Teacher': 6, 'Business Owner': 7, 'Scientist': 8,
        'Banker': 9, 'Writer': 10, 'Accountant': 11, 'Designer': 12,
        'Construction Engineer': 13, 'Game Developer': 14, 'Stock Investor': 15,
        'Real Estate Developer': 16
    }
'''
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2,
        'Software Engineer': 3, 'Teacher': 4, 'Business Owner': 5, 'Scientist': 6,
        'Banker': 7, 'Writer': 8, 'Accountant': 9
    }

# Apply mapping to the DataFrame
df['gender'] = df['gender'].map(gender_map)
df['part_time_job'] = df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_activities_map)
df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [42]:
df.head(100)

absence_days  biology_score  career_aspiration  chemistry_score  \
0               3             63                  0               97   
1               2             99                  1               80   
2               9             65                  2               96   
6               3             88                  3               73   
7               2             84                  3               63   
..            ...            ...                ...              ...   
140             0             77                  3               81   
142             1             60                  0               96   
143             3             80                  3               99   
146             8             68                  5               93   
147             0             96                  0               79   

     economics_score  english_score  extracurricular_activities  gender  \
0                0.0             90                           1       0   
1                0.0             73                           0       1   
2                0.0             76                           1       1   
6                0.0             76                           1       0   
7                0.0             70                           1       0   
..               ...            ...                         ...     ...   
140              0.0             67                           0       0   
142              0.0             90                           1       1   
143              0.0             80                           1       0   
146              0.0             58                           1       0   
147              0.0             85                           1       0   

     geography_score  history_score  math_score  part_time_job  physics_score  \
0                 87             90          73              0             93   
1                 63             67          82              0             78   
2                 87             91          81              0             95   
6                 64             96          98              0             89   
7                 85             95          92              1             94   
..               ...            ...         ...            ...            ...   
140               93             69          91              0             89   
142              100             94          70              0             79   
143               75             68          93              0             92   
146               72             97          73              0             51   
147               74             95          92              0             65   

     weekly_self_study_hours  total_score  average_score  
0                         27        593.0         74.125  
1                         47        542.0         67.750  
2                         13        591.0         73.875  
6                         25        584.0         73.000  
7                         30        583.0         72.875  
..                       ...          ...            ...  
140                       36        567.0         70.875  
142                       29        589.0         73.625  
143                       36        587.0         73.375  
146                        2        512.0         64.000  
147                       34        586.0         73.250  

[100 rows x 16 columns]

# Balance Dataset

In [43]:
df['career_aspiration'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
df['career_aspiration'].value_counts()

career_aspiration
3    315
5    309
7    169
0    138
9    126
1    119
2     61
4     59
6     39
8     32
Name: count, dtype: int64

In [45]:

from imblearn.over_sampling import SMOTE

# Create SMOTE object
smote = SMOTE(random_state=42)

# Separate features and target variable
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

# Apply SMOTE to the data
X_resampled, y_resampled = smote.fit_resample(X, y)




# Train test Split

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, random_state=42)

In [47]:
X_train.shape

(2520, 15)

# Feature Scalling

In [48]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [49]:
X_train_scaled.shape

(2520, 15)

# Models Training (Multiple Models)

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train_scaled, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test_scaled)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)


Model: Logistic Regression
Accuracy: 0.9142857142857143
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.90      0.92        68
           1       1.00      1.00      1.00        65
           2       0.95      0.97      0.96        60
           3       0.81      0.93      0.87        61
           4       0.88      0.86      0.87        65
           5       0.99      0.99      0.99        71
           6       0.92      0.97      0.94        60
           7       0.73      0.56      0.63        59
           8       0.88      0.95      0.92        63
           9       1.00      1.00      1.00        58

    accuracy                           0.91       630
   macro avg       0.91      0.91      0.91       630
weighted avg       0.91      0.91      0.91       630

Confusion Matrix:
 [[61  0  0  2  0  0  0  1  4  0]
 [ 0 65  0  0  0  0  0  0  0  0]
 [ 0  0 58  0  2  0  0  0  0  0]
 [ 1  0  0 57  0  0  0  3  0  0]
 [ 0  0  0

# Model Selection (Random Forest)

In [51]:
model =  RandomForestClassifier()

model.fit(X_train_scaled, y_train)
# Predict on test set
y_pred = model.predict(X_test_scaled)

# Calculate metrics
print("Accuracy: ",accuracy_score(y_test, y_pred))
print("Report: ",classification_report(y_test, y_pred))
print("Confusion Matrix: ",confusion_matrix(y_test, y_pred))

Accuracy:  0.9809523809523809
Report:                precision    recall  f1-score   support

           0       0.96      1.00      0.98        68
           1       1.00      1.00      1.00        65
           2       0.98      1.00      0.99        60
           3       0.92      0.97      0.94        61
           4       1.00      1.00      1.00        65
           5       1.00      1.00      1.00        71
           6       0.98      0.98      0.98        60
           7       0.98      0.85      0.91        59
           8       0.98      1.00      0.99        63
           9       1.00      1.00      1.00        58

    accuracy                           0.98       630
   macro avg       0.98      0.98      0.98       630
weighted avg       0.98      0.98      0.98       630

Confusion Matrix:  [[68  0  0  0  0  0  0  0  0  0]
 [ 0 65  0  0  0  0  0  0  0  0]
 [ 0  0 60  0  0  0  0  0  0  0]
 [ 1  0  0 59  0  0  0  1  0  0]
 [ 0  0  0  0 65  0  0  0  0  0]
 [ 0  0  0  0  0 7

# Single Input Predictions

In [52]:
# test 1
print("Actual Label :", y_test.iloc[10])
print("Model Prediction :",model.predict(X_test_scaled[10].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 6
Model Prediction : 6
Wow! Model doing well.....


In [53]:
# test 2
print("Actual Label :", y_test.iloc[300])
print("Model Prediction :",model.predict(X_test_scaled[300].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 7
Model Prediction : 3
Wow! Model doing well.....


In [54]:
# test 2
print("Actual Label :", y_test.iloc[23])
print("Model Prediction :",model.predict(X_test_scaled[23].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 4
Model Prediction : 4
Wow! Model doing well.....


# Saving & Load Files

In [55]:
import pickle

# SAVE FILES
pickle.dump(scaler,open("Models/scaler.pkl",'wb'))
pickle.dump(model,open("Models/model.pkl",'wb'))

In [56]:

# Load the scaler, label encoder, and model
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))

# Recommendation System

In [57]:
import pickle
import numpy as np

# Load the scaler, label encoder, model, and class names
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))
class_names = ['Lawyer', 'Doctor', 'Government Officer', 
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant']
'''class_names = ['Lawyer', 'Doctor', 'Government Officer', 'Artist',
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant', 'Designer',
               'Construction Engineer', 'Game Developer', 'Stock Investor',
               'Real Estate Developer']'''

def Recommendations(gender, part_time_job,absence_days, extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, economics_score,physics_score,
                    chemistry_score, biology_score, english_score, geography_score,
                   total_score,average_score):

    # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0
    
    # Create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded,absence_days,extracurricular_activities_encoded,
                               weekly_self_study_hours, math_score, history_score, economics_score,physics_score,
                               chemistry_score, biology_score, english_score, geography_score,
                               total_score,average_score]])
    
    # Scale features
    scaled_features = scaler.transform(feature_array)
    
    # Predict using the model
    probabilities = model.predict_proba(scaled_features)
    
    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:5]
    top_classes_names_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]
    
    return top_classes_names_probs

In [58]:
# Example usage 1
final_recommendations = Recommendations(gender='female',
                                        part_time_job=False,
                                        absence_days=4,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=20,
                                        math_score=98,
                                        history_score=34,
                                        economics_score=30,
                                        physics_score=97,
                                        chemistry_score=94,
                                        biology_score=45,
                                        english_score=90,
                                        geography_score=30,
                                        total_score=518,
                                        average_score=64.75
                            )

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
Software Engineer with probability 0.48
Banker with probability 0.24
Lawyer with probability 0.09
Accountant with probability 0.07
Business Owner with probability 0.06


In [59]:
# Example usage 2
final_recommendations = Recommendations(gender='male',
                                        part_time_job=False,
                                         absence_days=4,
                                        extracurricular_activities=True,
                                        weekly_self_study_hours=4,
                                        math_score=97,
                                        history_score=73,
                                        physics_score=18,
                                        chemistry_score=9,
                                        biology_score=56,
                                        english_score=60,
                                        economics_score=65,
                                        geography_score=77,
                                        total_score=530,
                                        average_score=66.25       
                                    )

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")


Top recommended studies with probabilities:
Doctor with probability 0.24
Banker with probability 0.22
Teacher with probability 0.18
Business Owner with probability 0.13
Software Engineer with probability 0.08


In [60]:
# sklear version in pychar production 
import sklearn
print(sklearn.__version__)
# in pycharm env install
# pip install scikit-learn==1.3.2

1.6.1


In [61]:
# Example usage 2
final_recommendations = Recommendations(gender='Male',
                                        part_time_job=False,
                                         absence_days=4,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=3,
                                        math_score=0,
                                        history_score=3,
                                        physics_score=9,
                                        chemistry_score=10,
                                        biology_score=9,
                                        english_score=98,
                                        economics_score=4,
                                        geography_score=5,
                                        total_score=138,
                                        average_score=17.25     
                                    )

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")


Top recommended studies with probabilities:
Business Owner with probability 0.51
Teacher with probability 0.11
Banker with probability 0.1
Accountant with probability 0.09
Government Officer with probability 0.07
